# This workflow will do a clean install of dependencies, build the source code and run tests
# For more information see: https://github.com/oven-sh/setup-bun

name: build and test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - run: bun install --frozen-lockfile
      - run: bun run lint
      - run: bun test
